name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        goarch: [amd64, arm64]
        include:
          - os: ubuntu-latest
            goos: linux
          - os: macos-latest
            goos: darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o wordly-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wordly-${{ matrix.goos }}-${{ matrix.goarch }}
          path: wordly-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Tag Automatically
        run: |
          # Generate version tag based on run number
          VERSION=v1.${{ github.run_number }}  # Example: v1.1, v1.2, etc.
          git tag $VERSION  # Tag the current commit with the generated version
          git push origin $VERSION  # Push the tag to GitHub

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
