name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        goarch: [amd64, arm64]
        include:
          - os: ubuntu-latest
            goos: linux
          - os: macos-latest
            goos: darwin
          - os: windows-latest
            goos: windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o wordly-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wordly-${{ matrix.goos }}-${{ matrix.goarch }}
          path: wordly-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    name: Create Release
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
